### ISSUE TITLE
Trigger an event when an object has reached the server

### ISSUE THREAD

**Issue by anantn** [firebase/backbonefire#10]
In some cases it might be useful to know when a particular model has been written to the server (as opposed to just locally), similar to the onComplete callback Firebase provides for push/set. We should expose this in Backfire through an appropriate event on the Collection/Model.

/cc @robv

**Comment by davideast** [comment]
Closing this for now. See #133 for more information. There's going to be an architectural shift towards proper extending of Backbone Models and Collections.
