### ISSUE TITLE
Error using Firebase Query in Firebase Collection

### ISSUE THREAD

**Issue by carnevalle** [firebase/backbonefire#126]
I am trying to use a Query on my collection like in this example:

```javascript
var TodoList = Backbone.Firebase.Collection.extend({
  url: new Firebase('https://<your-firebase>.firebaseio.com/todos').orderByChild('importance')
});
```

It returns an error because backbonefire.js tries to access .child() in line 753 while creating the Collection:

```javascript
newItem.firebase = self.firebase.child(newItem.id);
```

I have only fiddled with firebase and backbonefire for a few hours, so I don't know the API that well, but it seems like the orderByChild returns a Query-object and backbonefire expects a Firebase Reference. 

This seems to fix the issue (or at least not make it fail):
```javascript
newItem.firebase = self.firebase.ref().child(newItem.id);
```

Am I doing something wrong or is this a bug?

**Comment by davideast** [comment]
See #134.
