### ISSUE TITLE
Order[ing] not working?  / nextOrder moved to todo.js

### ISSUE THREAD

**Issue by voodoo** [firebase/backbonefire#127]
This is not an issue as much as a curiosity.

Messing around, trying to decide which tool I might use with firebase,  I noticed 'order' was not being updated on the model. Order was always zero (and was not used in the display so not really noticeable or needed). So I thought I would add it and sort in desc order to see if I could get the newest entry right below the input box.

I could update 'order' by moving nextOrder to todo.js. But I could not get/force ordering to work.

https://github.com/voodoo/backbonefire

I can't see the backend to confirm for sure 'order' is being set on  https://backbonefire.firebaseio.com/todos but when I change it to my own firebase it does update the 'order' value. But still I can't force it to sort by order. I tried a few things you will find in the diff.

https://github.com/voodoo/backbonefire/compare/firebase:master...master

Anyone run into this? Am I messing something up? Do I care ? :wink:

Cheers, Paul

**Comment by davideast** [comment]
Hi Paul,

Sorry that it took so long for me to respond to you. Order is set by using a query is with Firebase. Pass in a query reference to the Model/Collection and it will stay in order.

https://www.firebase.com/docs/web/guide/retrieving-data.html#section-queries
