### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by carnevalle** [firebase/backbonefire#129]
How do I go about authenticating through backbonefire? I have a JWT that I would like to authenticate with?

**Comment by davideast** [comment]
This is a subject that probably not the best format on GitHub. Adding an authentication example would be idea though. Can you try adding a question on Stackoverflow with some of the code you have written so far?

**Comment by carnevalle** [comment]
I think i'll try to send a pull request tomorrow with the code I got to work instead. :-)
