### ISSUE TITLE
Backbone.Firebase.Model#urlRoot doesn't work as described

### ISSUE THREAD

**Issue by costa** [firebase/backbonefire#131]
When returning something like `https://<your-firebase>.firebaseio.com/todos` from a Model's `#urlRoot`, a new object will have `todos` for `id` and `https://<your-firebase>.firebaseio.com/todos/todos` returned from (original) `#url`.
I would like to debug and contribute a PR, and as the first step, I'd like to play with this in your example app.
Unfortunately, I couldn't run it right away (it's all broken upon `grunt serve`), so I could really use some advice there.

**Comment by davideast** [comment]
>When returning something like https://<your-firebase>.firebaseio.com/todos from a Model's #urlRoot, a new object will have todos for id and https://<your-firebase>.firebaseio.com/todos/todos returned from (original) #url.

Can you provide a code sample? I think the issue you are referring to is fixed in the upcoming `0.5.1` release. Which should be going out this week.

>Unfortunately, I couldn't run it right away (it's all broken upon grunt serve), so I could really use some advice there.

What error do you receive? Did you setup the dependency managers: `npm i` and `bower i`?

**Comment by costa** [comment]
I believe I've managed to run everything locally.
Then, I've managed to break the todos example with a change set as small as this:
```diff
diff --git a/examples/todos/js/collections/todos.js b/examples/todos/js/collections/todos.js
index d5e18f3..27e7025 100644
--- a/examples/todos/js/collections/todos.js
+++ b/examples/todos/js/collections/todos.js
@@ -2,19 +2,14 @@
 define([
 	'underscore',
 	'backbone',
-	'models/todo',
-	'firebase',
-	'backbonefire'
+	'models/todo'
 ], function (_, Backbone, Todo) {
 	'use strict';

-	var TodosCollection = Backbone.Firebase.Collection.extend({
+	var TodosCollection = Backbone.Collection.extend({
 		// Reference to this collection's model.
 		model: Todo,

-		// Save all of the todo items under the `"todos"` namespace.
-		url: 'https://backbonefire.firebaseio.com/todos',
-
 		// Filter down the list of all todo items that are finished.
 		completed: function () {
 			return this.where({completed: true});
diff --git a/examples/todos/js/models/todo.js b/examples/todos/js/models/todo.js
index 53486bb..d25987a 100644
--- a/examples/todos/js/models/todo.js
+++ b/examples/todos/js/models/todo.js
@@ -1,11 +1,17 @@
 /*global define*/
 define([
 	'underscore',
-	'backbone'
+	'backbone',
+	'firebase',
+	'backbonefire'
 ], function (_, Backbone) {
 	'use strict';

-	var Todo = Backbone.Model.extend({
+	var Todo = Backbone.Firebase.Model.extend({
+
+		// Save all of the todo items under the `"todos"` namespace.
+		urlRoot: 'https://backbonefire.firebaseio.com/todos',
+
 		// Default attributes for the todo
 		// and ensure that each todo created has `title` and `completed` keys.
 		defaults: {
@@ -22,4 +28,4 @@ define([
 	});

 	return Todo;
-});
\ No newline at end of file
+});
diff --git a/examples/todos/js/views/app.js b/examples/todos/js/views/app.js
index ea6af97..d5a3c49 100644
--- a/examples/todos/js/views/app.js
+++ b/examples/todos/js/views/app.js
@@ -42,7 +42,7 @@ define([
 			this.listenTo(this.collection, 'filter', this.filterAll);
 			this.listenTo(this.collection, 'all', this.render);

-			this.collection.fetch();
+			// this.collection.fetch();
 		},

 		// Re-rendering the App just means refreshing the statistics -- the rest
```
I must note that the tests doesn't seem to include the `urlRoot` feature.

**Comment by davideast** [comment]
I've added a test for `urlRoot` for the upcoming release.

**Comment by costa** [comment]
Good, thanks. I'll check in a week then.

**Comment by davideast** [comment]
It's update now. Let me know if you still have any issues.

**Comment by costa** [comment]
@davideast Please re-open this issue after you test the Todos app with the diff I've provided above — it doesn't work still (checked on master).

**Comment by costa** [comment]
A reminder to re-open the issue: @davideast Just letting you know that I've re-produced the problem with your example above, using the current master. I believe I can contribute corresponding tests next time I'll be dealing with Firebase.
