### ISSUE TITLE
Is there a way to get a disconnected error when offline?

### ISSUE THREAD

**Issue by mcfarljw** [firebase/backbonefire#138]
I've got an application that needs to work both online and offline. If it's able to sync then I want to load up differently than if it can't. Is there some kind of trigger or callback that fires when the device is offline or disconnected?

```
app.user.info.once('sync', function() {
    //return something when disconnected
}
app.user.info.once('error', function() {
    //return something when disconnected
}
```

To add to this I've also tried using the following fetch option callback (with autoSync false). The success callback files, but error never seems to even when disconnected from the internet.

```
app.user.info.fetch({
    error: function() { console.log('error'); },
    success: function() { console.log('success'); }
})
```

**Comment by serneelsalexis** [comment]
+1

**Comment by katowulf** [comment]
You're looking for `.info/connected`. This is covered under [offline capabilities](https://www.firebase.com/docs/web/guide/offline-capabilities.html) in the [core docs](https://www.firebase.com/docs/).
