### ISSUE TITLE
Typo on Firebase backboneFire Page

### ISSUE THREAD

**Issue by clintonhalpin** [firebase/backbonefire#139]
"checout the GitHub repository." :smile:

![screen shot 2015-02-26 at 2 07 08 pm](https://cloud.githubusercontent.com/assets/523933/6399538/fbfa087e-bdc0-11e4-93d9-8eaf6a0e6f2f.png)

**Comment by davideast** [comment]
Thank you! :smile: 

I'll get that fixed in the main Firebase website.

**Comment by davideast** [comment]
Fixed!
