### ISSUE TITLE
goOffline support

### ISSUE THREAD

**Issue by agruber** [firebase/backbonefire#140]
Is there a way I can send a autoSync:true collection offline with the Firebase goOffline() function?

**Comment by davideast** [comment]
Each collection/model has a `firebase` property. Any methods that currently lack first-class support in BackboneFire can be called from the `firebase` property.

```js
var Collection = Backbone.Firebase.Collection.extend({
   url: '<firebase-url>'
});
var collection = new Collection();
collection.firebase.goOffline();
```

I'll add an issue to take a look at supporting presence.
