### ISSUE TITLE
goOffline support

### ISSUE THREAD

**Issue by davideast** [firebase/backbonefire#141]

**Comment by agruber** [comment]
I tried to call the function collection.firebase.goOffline() but my collection.firebase does not seem to have this function, it's only this:
![screenshot from 2015-03-09 15 33 04](https://cloud.githubusercontent.com/assets/64104/6557001/083e9708-c672-11e4-804c-f704d2fc56b8.png)

**Comment by davideast** [comment]
Can you provide me the code or even better a working JSBin demo?

**Comment by agruber** [comment]
I tired to put it together here:
http://jsbin.com/kufisoyema/1/edit?html,console

**Comment by davideast** [comment]
Ah, I'm having a dull moment.

The current reference isn't required to go offline; as `goOffline` is a class level method.

```js
Firebase.goOffline();
```

This should work anywhere because Firebase is attached to the window.

**Comment by agruber** [comment]
I see. Thanks for looking into this so promptly.
