### ISSUE TITLE
Compatible with the new Firebase?

### ISSUE THREAD

**Issue by mbrevda** [firebase/backbonefire#152]
It seems the js sdk has been updated with the latest v3 changes. Is this project still compatible? 
Thanks!

**Comment by cpbotha** [comment]
Here's an (unofficial?) fork that seems to have firebase3 support: https://github.com/bobbyhubbard/backbonefire/tree/firebase3

Would be great to have official word from the GOOG mothership also!

**Comment by mbrevda** [comment]
Oh, cool. I hope someone can take a look!

**Comment by abehaskins** [comment]
Hey folks - I'm working on bringing this into the Firebase 3.0 world - but since we need to migrate off of `mockfirebase` for our tests that means it's quite a bit of work.

It's coming soon, but no clear timeline.

**Comment by mbrevda** [comment]
Thanks @abehaskins. Anything new at your end re: this?

**Comment by mohansn** [comment]
Thanks, @abehaskins !

**Comment by mbrevda** [comment]
What are you using instead of mockfirebase?

**Comment by mstronge** [comment]
Hey @abehaskins - Any update on this? Thanks

**Comment by taseenb** [comment]
Is this project still maintained? Looks like it's abandoned. Thanks

**Comment by jpventura** [comment]
@taseenb, @abehaskins replied on twitter that the project is still maintained and that would make some updates next week.

Many development dependency libraries are deprecated, so I submitted the PR #158 updating them and fixing Travis CI test setup issues.

I don't know how long Firebase team will take to integrate the modifications, thus I have already integrated them into [my fork](https://github.com/jpventura/backbonefire)

**Comment by AniX** [comment]
Is there any update regarding the progress? Thanks!

**Comment by jpventura** [comment]
@abehaskins, any updates on #158 ?

**Comment by mbrevda** [comment]
I don't believe this repo will be updated. Backbone is kind of outdated and if you can, you should probably consider using an up to date js lib. If you DO want to go with backbone, you should still look integrate backbone and firebase "manually" and not really on the magic this repo provided. From experience, that was a huge mistake.

**Comment by mbrevda** [comment]
In a nutshell, there was too much "magic". Also, mapping a record to a collection/models as well as partial updates of a record works most of the time for some of the things... but just becomes more of a pain then it's worth. I found it way simpler to just set up listeners and then manually update collections/models (with the ability to normalize data as needed).
